env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: [ 1, { "extensions": [ ".js", ".jsx" ] } ]
