env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: "off"
  import/no-unresolved: "off"
  indent: ["error", 4]
  linebreak-style: "warn"
  react/react-in-jsx-scope: "off"
  react/jsx-filename-extension: ["warn", { "extensions": [ ".js", ".jsx" ] } ]
  react/jsx-indent: ["error", 4, { indentLogicalExpressions: true }]
  react/jsx-indent-props: ["off", 4]
  react/jsx-props-no-spreading: "off"
  react/prop-types: "off"
